import os
from dotenv import load_dotenv

load_dotenv()

CONFIG__SECRET_KEY = os.getenv("CONFIG__SECRET_KEY")
CONFIG__DEBUG = os.getenv("CONFIG__DEBUG")
CONFIG__PROJECT_DOMAIN_NAME = os.getenv("CONFIG__PROJECT_DOMAIN_NAME")

CONFIG__ROTATE_REFRESH_TOKENS = os.getenv("CONFIG__ROTATE_REFRESH_TOKENS")
CONFIG__BLACKLIST_AFTER_ROTATION = os.getenv("CONFIG__BLACKLIST_AFTER_ROTATION")

CONFIG__DB_NAME = os.getenv("CONFIG__DB_NAME")
CONFIG__DB_USER = os.getenv("CONFIG__DB_USER")
CONFIG__DB_PASS = os.getenv("CONFIG__DB_PASS")
CONFIG__DB_HOST = os.getenv("CONFIG__DB_HOST")
CONFIG__DB_PORT = os.getenv("CONFIG__DB_PORT")